service:
  name: atlas

package:
  individually: false
  include:
    - src/**

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-iamroles:
    defaultInherit: true
  prune:
    automatic: true
    number: 3

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-iamroles
  - serverless-prune-plugin
  - serverless-plugin-tracing
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  frameworkVersion: ‘1.64.1’
  stage: ${opt:stage, 'local'}
  region: ${opt:region, 'us-east-1'}
  timeout: 900
  apiGateway:
    minimumCompressionSize: 1024
  environment:
    DEBUG: '*'
    NODE_ENV: ${self:provider.stage}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  tracing:
    lambda: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource: "*"

functions:
  validateAuth:
    handler: src/functions/validateAuth.handle
  authenticate:
    handler: src/functions/authenticate.handle
    environment:
      PRIVATE_KEY: ${env:PRIVATE_KEY}
    events:
      - http:
          path: /authenticate
          method: POST
          cors: true
  me:
    handler: src/functions/getUserInfo.handle
    events:
      - http:
          path: /me
          method: GET
          cors: true
          authorizer: validateAuth

  resources:
    Resources:
      GatewayResponse:
        Type: 'AWS::ApiGateway::GatewayResponse'
        Properties:
          ResponseParameters:
            gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
            gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
          ResponseType: EXPIRED_TOKEN
          RestApiId:
            Ref: 'ApiGatewayRestApi'
          StatusCode: '401'
      AuthFailureGatewayResponse:
        Type: 'AWS::ApiGateway::GatewayResponse'
        Properties:
          ResponseParameters:
            gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
            gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
          ResponseType: UNAUTHORIZED
          RestApiId:
            Ref: 'ApiGatewayRestApi'
          StatusCode: '401'
