name: Deploy Prod

on:
  push:
    tags:
      - 'v**'

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      uses: bahmutov/npm-install@v1

    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
